// Dummy TH Sarabun registrar for jsPDF.
// Replace this file with a real base64 font registrar when ready.
// Usage in components: we will try to setFont('THSarabun') only if registered.
export default function registerTHSarabun() {
  // Intentionally empty. You can later paste code generated by jsPDF fontconverter:
  //   doc.addFileToVFS('THSarabun.ttf', '<base64>');
  //   doc.addFont('THSarabun.ttf', 'THSarabun', 'normal');
  // Note: registration must happen on a jsPDF instance.
}